### ISSUE TITLE
ripienaar/concat dependency snuck into the released version

### ISSUE THREAD

**Issue by smerrill** [example42/puppet-iptables#59]
Just like https://github.com/example42/puppet-sudo/issues/20, the latest example42/iptables has a dependency on ripienaar/concat. See https://forge.puppetlabs.com/example42/iptables/dependencies.

**Comment by jonoterc** [comment]
Any chance of this getting a new tag/release pushed to the puppet forge?  Thanks!

**Comment by javanthropus** [comment]
We're hitting this where I work as well.

**Comment by alvagante** [comment]
Ok, published finally an updated version... had some issues with the publishing script, so there are some useless version bumps.
Sorry for delay, let me know if this can be closed.

**Comment by javanthropus** [comment]
The fix looks to be working for us.  Thanks!
