### ISSUE TITLE
iptables-persistent service has been split+renamed in debian 8 (jessie)

### ISSUE THREAD

**Issue by lucab** [example42/puppet-iptables#66]
The debian-specific part of this module should be updated in order to work with latest debian release (jessie).

Relevant changes:
 *  persistent functionalities has been split across two binary packages
 * `iptables-persistent` does not provide anymore a init.d service file
 * both `iptables-persistent` and `netfilter-persistent` should be ensured installed to get the same functionality
 * service is now called `netfilter-persistent`

If you want to check for package version, split happened in revision `1.0`.
See [changelog](http://metadata.ftp-master.debian.org/changelogs/main/i/iptables-persistent/unstable_changelog) for more info.

**Comment by gvarisco** [comment]
@alvagante told me to kindly patch it yourself! <3

**Comment by gehel** [comment]
Not sure I understand the issue fully, but it seems that the same fix should be applied for Ubuntu Vivid (15.04)

**Comment by lucab** [comment]
@gehel yes, most probably it will affect all [Debian derivatives](https://wiki.debian.org/Derivatives/Census). Moreover, checking for OS version (instead of candidate package version) will break on backported packages.
